# Generated by Django 5.0.7 on 2024-07-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='garageNumber',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
