# Generated by Django 5.0.7 on 2024-08-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_units_client_end_dates_client_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='end_dates',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='start_date',
        ),
        migrations.AddField(
            model_name='client',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reference_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.units'),
        ),
    ]
