# Generated by Django 5.0.7 on 2024-08-02 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.garage'),
        ),
        migrations.AddField(
            model_name='garage',
            name='occupied',
            field=models.BooleanField(null=True),
        ),
    ]
