# Generated by Django 5.0.7 on 2024-08-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_client_in_gar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='garage_num',
            field=models.IntegerField(null=True),
        ),
    ]
