# Generated by Django 5.0.7 on 2024-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_client_garage_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invalid',
            field=models.BooleanField(null=True),
        ),
    ]
