# Generated by Django 5.0.7 on 2024-08-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_client_invalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='garage',
        ),
    ]
