# Generated by Django 5.0.7 on 2024-08-09 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_remove_client_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.units'),
        ),
    ]
