# Generated by Django 5.0.7 on 2024-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_client_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='unit',
            field=models.TextField(null=True),
        ),
    ]
