# Generated by Django 5.0.7 on 2024-08-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_client_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reservation',
        ),
        migrations.AddField(
            model_name='client',
            name='end_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='start_date',
            field=models.TextField(null=True),
        ),
    ]
