# Generated by Django 5.0.7 on 2024-08-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_remove_client_reservation_client_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='in_gar',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='occupied',
        ),
        migrations.RemoveField(
            model_name='units',
            name='short',
        ),
    ]
